### ISSUE TITLE
Leak Sensor data is not refreshing

### ISSUE THREAD

**Issue by jamesngob** [homebridge-plugins/homebridge-resideo#373]
**Describe The Bug:**

The temperature and humidity reading will not be updated according to the Honeywell Home Leak Detector. The value will only be updated if I restart the homebridge
**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-honeywell-leak tokens.
```

**Screenshots:**

**Thermostat Model:**

# **Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Honeywell Leak Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by donavanbecker** [comment]
@jamesngob I have pushed a beta for `homebridge-honeywell-home` plugin.

Do you have Homebridge UI?

if so it is really easy to install the latest beta. See Below:

<img width="706" alt="Screen Shot 2020-12-30 at 11 50 31 AM" src="https://user-images.githubusercontent.com/9875439/103371496-397ce100-4a95-11eb-95f9-345926631dce.png">
<img width="511" alt="Screen Shot 2020-12-30 at 11 50 42 AM" src="https://user-images.githubusercontent.com/9875439/103371503-400b5880-4a95-11eb-9d48-8629e3859dde.png">
<img width="507" alt="Screen Shot 2020-12-30 at 11 50 58 AM" src="https://user-images.githubusercontent.com/9875439/103371519-4a2d5700-4a95-11eb-9f16-3c0115f15e65.png">

**Comment by jamesngob** [comment]
I have installed the beta version and will update you later. But thank you for the time support

**Comment by donavanbecker** [comment]
@jamesngob I don't think `v8.2.1-beta.1` will work. I have just pushed `v8.2.1-beta.3`, please give that a try and report back.

**Comment by jamesngob** [comment]
@donavanbecker: the 1st beta did not work, you were right.
I just installed .beta.3 so in the next few hours, I will let you know if it's updated
Thanks again

**Comment by donavanbecker** [comment]
@jamesngob, I think we are good.

The one on the left is from last night, and the one on the right is from this morning. I didn't restart homebridge.


<p align="left">

<img src="https://user-images.githubusercontent.com/9875439/103413652-22df9400-4b40-11eb-860f-4587e80546e8.png" width="300px">
<img src="https://user-images.githubusercontent.com/9875439/103413655-2410c100-4b40-11eb-9a97-19eb8ab26f8d.png" width="300px">
<img src="https://user-images.githubusercontent.com/9875439/103413654-2410c100-4b40-11eb-8479-ec96c38ffe6e.png" width="300px">
<img src="https://user-images.githubusercontent.com/9875439/103413656-24a95780-4b40-11eb-9f3e-bd2c42aaa35d.png" width="300px">

</p>

**Comment by jamesngob** [comment]
@donavanbecker: I have seen the same result on my homebridge as well... However, one thing I noticed that because I selected the Celcius so the number got round up e.g. 4.9 C -> 5C and 65% ->66%... is it normal? I will wait for another update this afternoon to see. I will keep you posted

**Comment by jamesngob** [comment]
@donavanbecker: Just one more thing: in my Home App screen, I only see 2 icons: Humidity Sensor and Temperature sensor. I did not see "Leak Sensor" icon as shown in yours... Am I missing anything here? I only have the Honeywell Water Leak detector, no thermostat, no other product from Honeywell though

**Comment by donavanbecker** [comment]
@jamesngob, since iOS 14 hides all sensors from being tiles in the home app, they are kind of hidden, this is how you can find them:

1. Go to Home settings.
2. Find the Bridges section. (you will see your homebridge in there.)
3. Click on your homebridge.
4. Click on the homebridge accessories. (you should see all accessories that are being displayed by your homebridge.)
5.  Click on the Leak Sensor.
6. Click on the Accessories of the Leak Sensor
7.  You should see the 3 Services.

<p align="left">
<img src="https://user-images.githubusercontent.com/9875439/103425509-5807d880-4b78-11eb-801d-3865f8a09efd.jpg" width="250px">
<img src="https://user-images.githubusercontent.com/9875439/103425598-e8deb400-4b78-11eb-8fac-5f4ac7517d1f.jpg" width="250px">
<img src="https://user-images.githubusercontent.com/9875439/103425696-c600cf80-4b79-11eb-92ed-582ffe7daf3b.jpg" width="250px">
<img src="https://user-images.githubusercontent.com/9875439/103425513-5a6a3280-4b78-11eb-9129-d4faf9625cc7.jpg" width="250px">
<img src="https://user-images.githubusercontent.com/9875439/103425514-5b02c900-4b78-11eb-8363-a81527645752.jpg" width="250px">
<img src="https://user-images.githubusercontent.com/9875439/103425515-5b02c900-4b78-11eb-87f2-289db8ad5898.jpg" width="250px">
<img src="https://user-images.githubusercontent.com/9875439/103425516-5b9b5f80-4b78-11eb-8aa4-5a75cf54e66d.PNG" width="250px">

</p>

**Comment by jamesngob** [comment]
@donavanbecker Thank you very much for your details instruction. I found out these hidden sensors, nested too deep in there!
Thanks again, you rock!

**Comment by jamesngob** [comment]
@donavanbecker After 2 days of 6 times updates, I could confirm that it works now. Whenever there's update, the plugin will refresh and get the new readings. Great work!!!
Only thing worth mentioned here is that, if you change the unit of measurement to Celcius, the Temperature reading would be rounded up to 0.5 stop and the humidity would be added +/-1%
But overall, all good

**Comment by donavanbecker** [comment]
@jamesngob I created a new issue for this. I will release this to `@latest` soon. Then I will also update the [leak sensor plugin](https://github.com/donavanbecker/homebridge-honeywell-leak), if you would prefer to just have a plugin only for the leak sensor.

Then I will work on fixing the display issue #378. If you can display more details that would help, if not I can look into it further.
